### ISSUE TITLE
Failed to load a language-apertium package grammar

### ISSUE THREAD

**Issue by cayoh1** [mr-martian/language-apertium#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.1
**Thrown From**: [language-apertium](https://github.com/mr-martian/language-apertium) package 0.0.11

### Stack Trace

Failed to load a language-apertium package grammar

```
At The module '/Users/christineayoh/.atom/packages/language-apertium/node_modules/tree-sitter-twolc/build/Release/tree_sitter_twolc_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/christineayoh/.atom/packages/language-apertium/grammars/twolc.cson

Error: The module '/Users/christineayoh/.atom/packages/language-apertium/node_modules/tree-sitter-twolc/build/Release/tree_sitter_twolc_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/language-apertium/node_modules/tree-sitter-twolc/index.js:2:20)
    at /packages/language-apertium/node_modules/tree-sitter-twolc/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:756275)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3291750)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:362405)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:362246
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:584869
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /packages/language-apertium/grammars/twolc.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
ftp-remote-edit 0.18.1 
graphql-toolkit 0.1.0 
intentions 1.1.5 
language-apertium 0.0.11 
language-babel 2.85.0 
language-graphql 1.0.0 
linter 3.3.1 
linter-ui-default 3.3.1 
prettier-atom 0.60.1 
remote-edit-ni 3.6.0 
tabs-to-spaces 1.0.5 
teletype 0.13.4 
```

**Comment by mr-martian** [comment]
What happens if you run `npm rebuild` in `/Users/christineayoh/.atom/packages/language-apertium` as it suggests?

**Comment by cayoh1** [comment]
After running `npm rebuild` it still shows the same message

**Comment by mr-martian** [comment]
Upon further investigation, it turns out that the version of Node.js used to compile the grammars is wrong. Unfortunately, if you simply upgrade to the latest version, you get the same error but with `83` instead of `73`.

According to https://nodejs.org/en/download/releases/ `NODE_MODULE_VERSION 80` doesn't seem to exist.
